version: '3'

services:
  web:
    container_name: django_app
    build:
      dockerfile: ./Dockerfile
      context: .
    volumes:
      - ./:/usr/prod_api/
    ports:
      - "8000:8000"
    depends_on:
      - db
      - localstack
    environment:
      DB_NAME: "production"
      DB_USER_NAME: "root"
      DB_USER_PASSWORD: "123"
      DB_HOST: "db"
      DB_PORT: "3306"
      ENDPOINT_AWS_S3: "http://localstack:4566"
    command: sh -c "python manage.py runserver 0.0.0.0:8000"

  # MySQL database
  db:
    container_name: mysql_db
    image: "mysql:latest"
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: "production"
      MYSQL_ROOT_PASSWORD: "123"
    expose:
      - 3306
    ports:
      - 3366:3306
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 60s
      retries: 5

  # fake S3
  localstack:
    container_name: localstack
    image: localstack/localstack
    expose:
      - 4566
    ports:
      - 4566:4566
    environment:
      - SERVICES=s3
      - AWS_ACCESS_KEY_ID=123
      - AWS_SECRET_ACCESS_KEY=123
      - ENDPOINT_AWS_S3=http://localstack:4577
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "${TMPDIR:-/tmp}/localstack:/var/lib/localstack"
      - ./localstack/ready.sh:/etc/localstack/init/ready.d/init-aws.sh
      - localstack_data:/tmp/localstack
volumes:
  static:
  localstack_data:
